fix(backend): remove unnecessary files
This commit fixes the following error:

```
! Unable to load application: NameError: uninitialized constant ApplicationCable::ActionCable
bundler: failed to load command: puma (/bundle/ruby/2.5.0/bin/puma)
NameError: uninitialized constant ApplicationCable::ActionCable
  /app/backend/app/channels/application_cable/channel.rb:4:in `<module:ApplicationCable>'
  /app/backend/app/channels/application_cable/channel.rb:3:in `<top (required)>'
  /bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
  /bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
  /bundle/ruby/2.5.0/gems/activesupport-5.2.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
  /bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:478:in `block (2 levels) in eager_load!'
  /bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:477:in `each'
  /bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:477:in `block in eager_load!'
  /bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:475:in `each'
  /bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:475:in `eager_load!'
  /bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/engine.rb:356:in `eager_load!'
  /bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/application/finisher.rb:69:in `each'
  /bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
  /bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `instance_exec'
  /bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:32:in `run'
  /bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
  /usr/local/lib/ruby/2.5.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.5.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `call'
  /usr/local/lib/ruby/2.5.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/lib/ruby/2.5.0/tsort.rb:226:in `tsort_each'
  /usr/local/lib/ruby/2.5.0/tsort.rb:205:in `tsort_each'
  /bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/initializable.rb:60:in `run_initializers'
  /bundle/ruby/2.5.0/gems/railties-5.2.1/lib/rails/application.rb:361:in `initialize!'
  /app/backend/config/environment.rb:7:in `<top (required)>'
  config.ru:5:in `require_relative'
  config.ru:5:in `block in <main>'
  /bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `instance_eval'
  /bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:55:in `initialize'
  config.ru:in `new'
  config.ru:in `<main>'
  /bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `eval'
  /bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:49:in `new_from_string'
  /bundle/ruby/2.5.0/gems/rack-2.0.6/lib/rack/builder.rb:40:in `parse_file'
  /bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:318:in `load_rackup'
  /bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/configuration.rb:243:in `app'
  /bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/runner.rb:145:in `load_and_bind'
  /bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/single.rb:96:in `run'
  /bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/launcher.rb:184:in `run'
  /bundle/ruby/2.5.0/gems/puma-3.12.0/lib/puma/cli.rb:78:in `run'
  /bundle/ruby/2.5.0/gems/puma-3.12.0/bin/puma:10:in `<top (required)>'
  /bundle/ruby/2.5.0/bin/puma:23:in `load'
  /bundle/ruby/2.5.0/bin/puma:23:in `<top (required)>'
```