fix(frontend): use _.forEach for iterating over elements of the object
This commit fixes the following type error:

```
__tests__/components/pages/signup.test.tsx:11:19 - error TS7017: Element implicitly has an 'any' type because type 'FormValues' has no index signature.

11     const value = values[key]
                     ~~~~~~~~~~~
```