fix(frontend): import missing react
This commit fixes an following error:
```
error TS2686: 'React' refers to a UMD global, but the current file is a module. Consider adding an import instead.
```