fix(frontend): avoid redundant `keyof`
This commit also fixes the following type error:

```
components/molecules/ResultTable.tsx:38:29 - error TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.

38     clearLamp.backgroundCSS[props.clearLamp || 'default']}
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```