fix(frontend): specify the type of the enum key
This commit fixes the following type error:

```
pages/map.tsx:35:13 - error TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.

35   PlayStyle[pascalize(playStyle)]
               ~~~~~~~~~~~~~~~~~~~~

pages/map.tsx:38:14 - error TS7015: Element implicitly has an 'any' type because index expression is not of type 'number'.

38   Difficulty[pascalize(difficulty)]
                ~~~~~~~~~~~~~~~~~~~~~
```